# WebSlinger Stored Procedure Bundle Configuration
web_slinger:
    stored_procedure:
        hostname: '%env(WEB_SLINGER_SP_HOST)%'
        username: '%env(WEB_SLINGER_SP_USERNAME)%'
        password: '%env(WEB_SLINGER_SP_PASSWORD)%'