services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WebSlinger\StoredProcedureFactory\StoredProcedureFactory:
        arguments:
            $hostname: '%webslinger.stored_procedure.hostname%'
            $username: '%webslinger.stored_procedure.username%'
            $pwd: '%webslinger.stored_procedure.password%'
        public: true

    WebSlinger\StoredProcedureFactory\Command\InstallCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: 'console.command' }